### ISSUE TITLE
Patient/SCID Info: Currently on Active Duty

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#152]
Radio: Yes, No, default is no

**Comment by emilyville** [comment]
I think this may have been added and was slightly misconstrued in implementation:
![screen shot 2015-07-15 at 3 29 11 pm](https://cloud.githubusercontent.com/assets/1307774/8711412/87dd6f90-2b06-11e5-9544-1ac7d479212f.png)

I only see one "active duty" item on the spreadsheet, we should edit this one instead to be consistent with this ticket instead of adding a new one, @kathytpham ?

**Comment by kathypham-gov** [comment]
Both spreadsheets look like they say "Currently on Active Duty", not "Is Injured on Active Duty." Let's update. I thought I saw "Is Injured on Active Duty" somewhere, but I can't find it anywhere now. @emilyville

**Comment by emilyville** [comment]
@kathytpham The more I think about it.. "Injured on active duty" did come up a few times, but when we got into the details this was for answering other questions, like "is travel covered?" and I believe we addressed all of those questions elsewhere. So if I understand your comment above, we'll update what's currently "injured on active duty" to "Currently on Active Duty".

**Comment by kathypham-gov** [comment]
@emilyville From those conversations, do you think it SHOULD be "injured on active duty"?

**Comment by emilyville** [comment]
I think injured in active duty is reflected here:
![screen shot 2015-07-15 at 5 27 17 pm](https://cloud.githubusercontent.com/assets/1307774/8712903/d56b26a2-2b16-11e5-9c6e-ddb2bc4d5958.png)
Though it is (randomly) in "contact info"
