### ISSUE TITLE
Create Fundamental User Journey - Nurses

### ISSUE THREAD

**Issue by iamkevinscott** [department-of-veterans-affairs/SCIInterim#42]
@pchunt Please work with Susy George regarding this assignment.  Once she has an account I will start assigning nurse related items to her.

“User Journeys” are part of the requirements gathering for application development.  These should just be rough first stabs scoping the domain of users (Nurses). 
- 2-3 sentences describing them
- What are the critical few tasks they are trying to achieve
- What answers are they trying to get from the application to do their jobs

**Comment by pchunt** [comment]
Morning Kevin and Albert,

Can we hold off this till next week? I have asked Albert to do a demonstration on how to register and use GITHUB as well as sharing with us the advantages of using GITHUB. Based on my experience so far, we use so many desktop applications on a daily basis, I am not sure about adding one more. Moreover, my inbox has been inundated with alerts from GITHUB. Let Dr. Chun and Susy view the demonstration and decide whether or not they want to use this application.  I for one has not been fond of GITHUB so far, but this may due to my lack of knowledge of this application. That’s why I want to reserve my judgment and preference till Albert’s demonstration next week.

Thank you both and have a great weekend.

**Comment by awong-dev** [comment]
@pchunt We're conflating 2 things:
1. Getting the actual issue resolved (creating a user story)...which I think doesn't have anything to do with github.
2. Whether or not we use github.

Let's discuss github separately since it's unrelated to the topic of this issue which is need a user journey for nurses for the eHMP work.

**Comment by pchunt** [comment]
Got it. Thanks for the clarification Albert.

By the way, can you tell me what day next week will you be ready to show the review team the first version of the interim SCIDO? Can you also let me know of your available days/times to do the presentation? Please be informed of the following:

1.       Dr. Chun and Susy’s schedules are usually overbooked, so we do need some advanced notice to schedule anything in their schedule

2.       Most of the time neither of them and some days myself as well are working off site, so it is imperative the we can do this demonstration online so they can access it anywhere

3.       We have discussed the possibility of using a Non-VA Internet connection to view this demonstration. We do have this option at the VA Long Beach, but not sure of other VA. But we will figure this out once we have the date of the demonstration.

Kevin,
Just a heads up: for now the review team will be Dr. Chun, Suzy, me, you, Phil, Kendra, Latora, Yvonne, and Fatima. If you can think of one or two experienced MIO Coordinators who have been there since the beginning, can you send me their contact info?

We do want to keep this review team within manageable size, otherwise, too many cooks can spoil the broth.

Thank you both.

**Comment by awong-dev** [comment]
FYI, I'm deleting the last comment from Peter because it is not related to issue #42 about creating a user story for nurses.

Moving the discussion about demos, etc., back to e-mail.

**Comment by awong-dev** [comment]
Closing all non dev-team related issues since they aren't being tracked by github anymore.
